name: Build, test and deploy

on:
  push:
    branches: [cicd]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Pulls repository code into the runner server (Required to access files)
      - name: Checkout
        uses: actions/checkout@v4

      # Set up PHP environment (v8.3)
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: "8.3"

      - name: Create database
        run: touch ./database/database.sqlite

      - name: Copy .env
        run: cp .env.test .env

      - name: Install app
        run: composer install

      - name: Generate Application Key
        run: php artisan key:generate
      - name: Run Migrations
        run: php artisan migrate

      - name: Install Node.js dependencies
        run: npm ci

      - name: Build frontend assets
        run: npm run build

      - name: Test PHPstan
        run: ./vendor/bin/phpstan analyse

      - name: Test PHPUnit
        run: ./vendor/bin/phpunit

  deploy:
    needs: build # အပေါ်က build job (test တွေ) အောင်မြင်မှ ဒီအလုပ်ကို လုပ်မယ်
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to VPS via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USERNAME }}

          password: ${{ secrets.SSH_PASSWORD }}
          port: 22
          script: |
            # cd /var/www/cicd
            cd ${{ secrets.APP_PATH }}
            ./build.sh
